---
version: '3.8'

volumes:
  app-storage:

services:
  backend:
    image: hydra-backend
    build:
      context: ./services/backend
      args:
        BUNDLE_WITHOUT: '' # keep empty
        RAILS_ENV: development
    command: app
    volumes:
      - ./services/backend:/work
      - app-storage:/mnt/storage
    depends_on:
      - postgres
      - redis

  frontend:
    image: hydra-backend
    command: web
    user: root
    volumes:
      - ./services/backend:/work
      - app-storage:/mnt/storage
    depends_on:
      - backend
    ports:
      - 80:80

  # Misc Services

  postgres:
    image: public.ecr.aws/docker/library/postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: public.ecr.aws/docker/library/redis:7

  mail:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SMTP_AUTH_ACCEPT_ANY: 1
    ports:
      - 8025:8025

  vite:
    image: hydra-backend
    command: ./bin/vite dev
    volumes:
      - source: ./services/backend
        target: /opt/app
        type: bind
    ports:
      - 3036:3036
