---
version: '3.8'

volumes:
  app-storage:
  app-assets:

services:
  backend:
    image: hydra-backend
    build:
      context: ./services/backend
    command: app
    volumes:
      - ./services/backend:/opt/app
      - app-storage:/mnt/storage
    depends_on:
      - postgres
      - redis

  frontend:
    image: hydra-frontend
    build:
      context: ./services/frontend
    volumes:
      - ./services/frontend/config/nginx.conf:/etc/nginx/nginx.conf
      - ./services/frontend/dist:/opt/app/dist
      - app-storage:/mnt/storage
    ports:
      - 80:80

  vite:
    image: hydra-frontend
    command: npm run build -- --watch
    volumes:
      - source: ./services/frontend
        target: /opt/app
        type: bind

  # Misc Services

  postgres:
    image: public.ecr.aws/docker/library/postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: public.ecr.aws/docker/library/redis:7
