source 'https://rubygems.org'

ruby '3.2.3'

gem 'rails',  '~> 7'
gem 'pg',     '~> 1'
gem 'puma',   '>= 5'

gem 'bootsnap',         '~> 1', require: false
gem 'devise',           '~> 4'
gem 'devise_invitable', '~> 2'
gem 'devise-jwt',       '~> 0'
gem 'jbuilder',         '~> 2'
gem 'rack-cors',        '~> 2'
gem 'redis-rails',      '~> 5'

group :development, :test do
  gem 'pgreset'
  gem 'debug'
end
